In [1]:
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
base = pd.read_csv('sample_data/autos.csv', encoding = 'ISO-8859-1')

In [3]:
print(base)

                dateCrawled  ...             lastSeen
0       2016-03-24 11:52:17  ...  2016-04-07 03:16:57
1       2016-03-24 10:58:45  ...  2016-04-07 01:46:50
2       2016-03-14 12:52:21  ...  2016-04-05 12:47:46
3       2016-03-17 16:54:04  ...  2016-03-17 17:40:17
4       2016-03-31 17:25:20  ...  2016-04-06 10:17:21
...                     ...  ...                  ...
371523  2016-03-14 17:48:27  ...  2016-04-06 00:46:52
371524  2016-03-05 19:56:21  ...  2016-03-11 18:17:12
371525  2016-03-19 18:57:12  ...  2016-04-07 07:15:26
371526  2016-03-20 19:41:08  ...  2016-03-24 12:45:21
371527  2016-03-07 19:39:19  ...  2016-03-22 03:17:10

[371528 rows x 20 columns]


In [4]:
base.describe()

price  yearOfRegistration  ...  nrOfPictures    postalCode
count  3.715280e+05       371528.000000  ...      371528.0  371528.00000
mean   1.729514e+04         2004.577997  ...           0.0   50820.66764
std    3.587954e+06           92.866598  ...           0.0   25799.08247
min    0.000000e+00         1000.000000  ...           0.0    1067.00000
25%    1.150000e+03         1999.000000  ...           0.0   30459.00000
50%    2.950000e+03         2003.000000  ...           0.0   49610.00000
75%    7.200000e+03         2008.000000  ...           0.0   71546.00000
max    2.147484e+09         9999.000000  ...           0.0   99998.00000

[8 rows x 7 columns]

In [5]:
base = base.drop('dateCrawled', axis = 1)
base = base.drop('dateCreated', axis = 1)
base = base.drop('nrOfPictures', axis = 1)
base = base.drop('postalCode', axis = 1)
base = base.drop('lastSeen', axis = 1)

In [6]:
print(base)

                                                name  ... notRepairedDamage
0                                         Golf_3_1.6  ...               NaN
1                               A5_Sportback_2.7_Tdi  ...                ja
2                     Jeep_Grand_Cherokee_"Overland"  ...               NaN
3                                 GOLF_4_1_4__3TÜRER  ...              nein
4                     Skoda_Fabia_1.4_TDI_PD_Classic  ...              nein
...                                              ...  ...               ...
371523                    Suche_t4___vito_ab_6_sitze  ...               NaN
371524         Smart_smart_leistungssteigerung_100ps  ...              nein
371525            Volkswagen_Multivan_T4_TDI_7DC_UY2  ...              nein
371526                        VW_Golf_Kombi_1_9l_TDI  ...               NaN
371527  BMW_M135i_vollausgestattet_NP_52.720____Euro  ...              nein

[371528 rows x 15 columns]


In [7]:
base['name'].value_counts()

Ford_Fiesta                                                      657
BMW_318i                                                         627
Opel_Corsa                                                       622
Volkswagen_Golf_1.4                                              603
BMW_316i                                                         523
                                                                ... 
Volkswagen_Polo_CL_Coupé                                           1
Volkswagen_Golf_1.9_TDI_DSG_Sportline                              1
Audi_A5_RS5_Tdi                                                    1
Mercedes_Benz_A_Klasse_A140                                        1
722.626_Automatikgetriebe_Mercedes_Benz_W211_S211_W220_defekt      1
Name: name, Length: 233531, dtype: int64

In [8]:
base = base.drop('name', axis = 1)

In [9]:
base['seller'].value_counts()

privat        371525
gewerblich         3
Name: seller, dtype: int64

In [10]:
base = base.drop('seller', axis = 1)

In [11]:
base['offerType'].value_counts()

Angebot    371516
Gesuch         12
Name: offerType, dtype: int64

In [12]:
base = base.drop('offerType', axis = 1)

In [13]:
i1 = base.loc[base.price <= 10]

In [14]:
print(i1)

        price   abtest vehicleType  ...  fuelType           brand  notRepairedDamage
7           0     test   limousine  ...    benzin      volkswagen               nein
40          0     test         NaN  ...    benzin            opel                NaN
60          1  control         suv  ...       NaN  sonstige_autos                NaN
91          1  control   limousine  ...    diesel   mercedes_benz               nein
115         0     test         NaN  ...    benzin      volkswagen                NaN
...       ...      ...         ...  ...       ...             ...                ...
371356      0  control         NaN  ...       NaN            opel                 ja
371392      0     test  kleinwagen  ...    benzin            ford                NaN
371402      0  control  kleinwagen  ...    benzin          suzuki                NaN
371431      0  control  kleinwagen  ...    benzin            seat                 ja
371522      0  control         NaN  ...    benzin      mitsubishi

In [15]:
base = base[base.price > 10]

In [19]:
i2 = base.loc[base.price >= 350000]

In [20]:
print(i2)

           price   abtest  ...           brand  notRepairedDamage
1846      579000  control  ...             bmw               nein
10649     420000  control  ...         porsche               nein
14663   11111111  control  ...      volkswagen                NaN
16889    1000000  control  ...            ford                 ja
20143    1250000     test  ...         porsche               nein
...          ...      ...  ...             ...                ...
364171   3890000     test  ...  sonstige_autos               nein
365461    599000  control  ...             bmw               nein
366653  99999999  control  ...             bmw                NaN
366861   3895000     test  ...  sonstige_autos               nein
367041   1600000     test  ...  sonstige_autos               nein

[119 rows x 12 columns]


In [21]:
base = base.loc[base.price < 350000]

In [23]:
print(base)

        price   abtest vehicleType  ...  fuelType           brand  notRepairedDamage
0         480     test         NaN  ...    benzin      volkswagen                NaN
1       18300     test       coupe  ...    diesel            audi                 ja
2        9800     test         suv  ...    diesel            jeep                NaN
3        1500     test  kleinwagen  ...    benzin      volkswagen               nein
4        3600     test  kleinwagen  ...    diesel           skoda               nein
...       ...      ...         ...  ...       ...             ...                ...
371523   2200     test         NaN  ...       NaN  sonstige_autos                NaN
371524   1199     test      cabrio  ...    benzin           smart               nein
371525   9200     test         bus  ...    diesel      volkswagen               nein
371526   3400     test       kombi  ...    diesel      volkswagen                NaN
371527  28990  control   limousine  ...    benzin             bmw

In [24]:
base.loc[pd.isnull(base['vehicleType'])]

price   abtest vehicleType  ...  fuelType           brand  notRepairedDamage
0         480     test         NaN  ...    benzin      volkswagen                NaN
16        300     test         NaN  ...    benzin      volkswagen                NaN
22       2900     test         NaN  ...    benzin            opel               nein
26       5555  control         NaN  ...       NaN         citroen               nein
31        899  control         NaN  ...    benzin         renault                NaN
...       ...      ...         ...  ...       ...             ...                ...
371495    180  control         NaN  ...    benzin            opel                NaN
371504   2600  control         NaN  ...       NaN   mercedes_benz                NaN
371509   1900     test         NaN  ...       NaN      volkswagen               nein
371519   5250  control         NaN  ...       NaN      alfa_romeo               nein
371523   2200     test         NaN  ...       NaN  sonstige_autos                NaN

[33546 rows x 12 columns]

In [25]:
base['vehicleType'].value_counts()

limousine     93614
kleinwagen    78014
kombi         65921
bus           29699
cabrio        22509
coupe         18386
suv           14477
andere         3125
Name: vehicleType, dtype: int64

In [28]:
base.loc[pd.isnull(base['gearbox'])]

price   abtest vehicleType  ...  fuelType           brand  notRepairedDamage
15        450     test  kleinwagen  ...    benzin            ford                NaN
16        300     test         NaN  ...    benzin      volkswagen                NaN
32        245     test   limousine  ...    benzin      volkswagen               nein
37       1500     test         NaN  ...    diesel         renault               nein
70       1200     test       coupe  ...       NaN            opel                NaN
...       ...      ...         ...  ...       ...             ...                ...
371443   3300  control       kombi  ...    diesel      volkswagen                NaN
371460   3500  control         NaN  ...       NaN      volkswagen                NaN
371486    350  control  kleinwagen  ...       NaN            fiat                NaN
371495    180  control         NaN  ...    benzin            opel                NaN
371523   2200     test         NaN  ...       NaN  sonstige_autos                NaN

[17236 rows x 12 columns]

In [29]:
base['gearbox'].value_counts()

manuell      266547
automatik     75508
Name: gearbox, dtype: int64

In [30]:
base.loc[pd.isnull(base['model'])]

price   abtest vehicleType  ...  fuelType           brand  notRepairedDamage
1       18300     test       coupe  ...    diesel            audi                 ja
83        350  control  kleinwagen  ...       NaN            fiat                 ja
139      1450  control   limousine  ...       NaN            audi               nein
156      6799  control  kleinwagen  ...    benzin      volkswagen               nein
165       500  control  kleinwagen  ...    benzin         renault               nein
...       ...      ...         ...  ...       ...             ...                ...
371399    560  control  kleinwagen  ...    benzin            fiat                 ja
371476   9400  control       kombi  ...    diesel  sonstige_autos                 ja
371495    180  control         NaN  ...    benzin            opel                NaN
371509   1900     test         NaN  ...       NaN      volkswagen               nein
371523   2200     test         NaN  ...       NaN  sonstige_autos                NaN

[17967 rows x 12 columns]

In [31]:
base['model'].value_counts()

golf               28989
andere             25560
3er                19905
polo               12604
corsa              12149
                   ...  
serie_2                8
rangerover             6
serie_3                3
serie_1                1
discovery_sport        1
Name: model, Length: 251, dtype: int64

In [33]:
base.loc[pd.isnull(base['fuelType'])]

price   abtest vehicleType  ...  fuelType           brand  notRepairedDamage
9         999     test  kleinwagen  ...       NaN      volkswagen                NaN
13       2500  control       kombi  ...       NaN      volkswagen               nein
26       5555  control         NaN  ...       NaN         citroen               nein
36       1600  control      andere  ...       NaN            opel                NaN
41       7500  control   limousine  ...       NaN   mercedes_benz                NaN
...       ...      ...         ...  ...       ...             ...                ...
371496   3850     test      cabrio  ...       NaN         peugeot               nein
371504   2600  control         NaN  ...       NaN   mercedes_benz                NaN
371509   1900     test         NaN  ...       NaN      volkswagen               nein
371519   5250  control         NaN  ...       NaN      alfa_romeo               nein
371523   2200     test         NaN  ...       NaN  sonstige_autos                NaN

[29391 rows x 12 columns]

In [34]:
base['fuelType'].value_counts()

benzin     217582
diesel     106002
lpg          5222
cng           557
hybrid        271
andere        165
elektro       101
Name: fuelType, dtype: int64

In [35]:
base.loc[pd.isnull(base['notRepairedDamage'])]

price   abtest vehicleType  ...  fuelType           brand  notRepairedDamage
0         480     test         NaN  ...    benzin      volkswagen                NaN
2        9800     test         suv  ...    diesel            jeep                NaN
8       14500  control         bus  ...    benzin            ford                NaN
9         999     test  kleinwagen  ...       NaN      volkswagen                NaN
12        999  control       kombi  ...    benzin      volkswagen                NaN
...       ...      ...         ...  ...       ...             ...                ...
371507   5999     test       kombi  ...    diesel            audi                NaN
371514    999  control      cabrio  ...    benzin         renault                NaN
371515   1690     test       kombi  ...    benzin           skoda                NaN
371523   2200     test         NaN  ...       NaN  sonstige_autos                NaN
371526   3400     test       kombi  ...    diesel      volkswagen                NaN

[65986 rows x 12 columns]

In [36]:
base['notRepairedDamage'].value_counts()

nein    259301
ja       34004
Name: notRepairedDamage, dtype: int64

In [37]:
valores = {'vehicleType': 'limousine', 'gearbox': 'manuell',
           'model': 'golf', 'fuelType': 'benzin',
           'notRepairedDamage': 'nein'}
base = base.fillna(value = valores)

In [38]:
previsores = base.iloc[:, 1:13].values
preco_real = base.iloc[:, 0].values

In [39]:
print(previsores)

[['test' 'limousine' 1993 ... 'benzin' 'volkswagen' 'nein']
 ['test' 'coupe' 2011 ... 'diesel' 'audi' 'ja']
 ['test' 'suv' 2004 ... 'diesel' 'jeep' 'nein']
 ...
 ['test' 'bus' 1996 ... 'diesel' 'volkswagen' 'nein']
 ['test' 'kombi' 2002 ... 'diesel' 'volkswagen' 'nein']
 ['control' 'limousine' 2013 ... 'benzin' 'bmw' 'nein']]


In [40]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [49]:
onehotencoder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [0,1,3,5,8,9,10])],remainder='passthrough')
previsores = onehotencoder.fit_transform(previsores).toarray()

In [50]:
print(previsores)

[[0.00e+00 1.00e+00 0.00e+00 ... 0.00e+00 1.50e+05 0.00e+00]
 [0.00e+00 1.00e+00 0.00e+00 ... 1.90e+02 1.25e+05 5.00e+00]
 [0.00e+00 1.00e+00 0.00e+00 ... 1.63e+02 1.25e+05 8.00e+00]
 ...
 [0.00e+00 1.00e+00 0.00e+00 ... 1.02e+02 1.50e+05 3.00e+00]
 [0.00e+00 1.00e+00 0.00e+00 ... 1.00e+02 1.50e+05 6.00e+00]
 [1.00e+00 0.00e+00 0.00e+00 ... 3.20e+02 5.00e+04 8.00e+00]]


In [55]:
regressor = Sequential([
        tf.keras.layers.Dense(units=158, activation = 'relu', input_dim=316),
        tf.keras.layers.Dense(units=158, activation = 'relu'),
        tf.keras.layers.Dense(units=1, activation = 'linear')])

regressor.compile(loss = 'mean_absolute_error', optimizer = 'adam',
                  metrics = ['mean_absolute_error'])
regressor.fit(previsores, preco_real, batch_size = 300, epochs = 10)

Epoch 1/10
1198/1198 [==============================] - 8s 6ms/step - loss: 3839.6741 - mean_absolute_error: 3839.6741
Epoch 2/10
1198/1198 [==============================] - 7s 6ms/step - loss: 3391.6353 - mean_absolute_error: 3391.6353
Epoch 3/10
1198/1198 [==============================] - 7s 6ms/step - loss: 3103.3660 - mean_absolute_error: 3103.3660
Epoch 4/10
1198/1198 [==============================] - 7s 6ms/step - loss: 2917.2112 - mean_absolute_error: 2917.2112
Epoch 5/10
1198/1198 [==============================] - 7s 6ms/step - loss: 2817.2932 - mean_absolute_error: 2817.2932
Epoch 6/10
1198/1198 [==============================] - 7s 6ms/step - loss: 2746.6597 - mean_absolute_error: 2746.6597
Epoch 7/10
1198/1198 [==============================] - 7s 6ms/step - loss: 2713.7864 - mean_absolute_error: 2713.7864
Epoch 8/10
1198/1198 [==============================] - 7s 6ms/step - loss: 2676.0999 - mean_absolute_error: 2676.0999
Epoch 9/10
1198/1198 [==========================

In [60]:
previsoes = regressor.predict(previsores)

In [61]:
previsoes.mean()

6311.477

In [62]:
preco_real.mean()

5916.833945186492